name: Build and Generate Docs
on:
  push:
    branches:
      - master  # Replace with the name of your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Replace with the version of Node.js you need

      - name: Install dependencies
        run: npm install  # Replace with the actual command to install project dependencies

      - name: Build project
        run: npm run build:github  # Replace with the actual build command
